[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_core_collection = "ER9AadmM55TVTFQGz8YDS94pYwpMDD3BEMSHsRXxpj92"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/programs/mpl_core_program.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
